#!/usr/bin/env bash
# ============================================
# TMWS Git Hooks Installation Script
# ============================================
# Installs local git hooks for pre-push validation
# Replaces GitHub Actions with local-first workflow
#
# Usage:
#   bash scripts/git-hooks/install-hooks.sh
#
# What it does:
#   1. Creates .git/hooks/pre-push script
#   2. Makes script executable
#   3. Configures hook to run validator + reporter
#   4. Verifies installation
#
# Issue #55 Phase 2: GitHub-independent workflow
# ============================================

set -euo pipefail

# ============================================
# Configuration
# ============================================

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"
PRE_PUSH_HOOK="$HOOKS_DIR/pre-push"

VALIDATOR_SCRIPT="$PROJECT_ROOT/scripts/git-hooks/pre-push-validator.py"
REPORTER_SCRIPT="$PROJECT_ROOT/scripts/git-hooks/issue-reporter.py"

# ============================================
# Functions
# ============================================

log_info() {
    echo "[INFO] $*"
}

log_success() {
    echo "✅ $*"
}

log_error() {
    echo "❌ ERROR: $*" >&2
}

check_git_repo() {
    if [ ! -d "$PROJECT_ROOT/.git" ]; then
        log_error "Not a git repository: $PROJECT_ROOT"
        exit 1
    fi
    log_success "Git repository detected"
}

check_python() {
    if ! command -v python3 &> /dev/null; then
        log_error "python3 not found in PATH"
        exit 1
    fi
    log_success "Python 3 found: $(python3 --version)"
}

check_scripts_exist() {
    if [ ! -f "$VALIDATOR_SCRIPT" ]; then
        log_error "Validator script not found: $VALIDATOR_SCRIPT"
        exit 1
    fi

    if [ ! -f "$REPORTER_SCRIPT" ]; then
        log_error "Reporter script not found: $REPORTER_SCRIPT"
        exit 1
    fi

    log_success "Validation scripts found"
}

backup_existing_hook() {
    if [ -f "$PRE_PUSH_HOOK" ]; then
        BACKUP="$PRE_PUSH_HOOK.backup.$(date +%Y%m%d_%H%M%S)"
        log_info "Backing up existing pre-push hook to: $BACKUP"
        cp "$PRE_PUSH_HOOK" "$BACKUP"
    fi
}

create_pre_push_hook() {
    log_info "Creating pre-push hook..."

    mkdir -p "$HOOKS_DIR"

    cat > "$PRE_PUSH_HOOK" << 'EOF'
#!/usr/bin/env bash
# ============================================
# TMWS Pre-Push Git Hook
# ============================================
# Auto-generated by scripts/git-hooks/install-hooks.sh
# Issue #55 Phase 2: GitHub-independent workflow
# ============================================

set -euo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
VALIDATOR="$PROJECT_ROOT/scripts/git-hooks/pre-push-validator.py"
REPORTER="$PROJECT_ROOT/scripts/git-hooks/issue-reporter.py"

echo ""
echo "🔍 Running pre-push validation..."
echo ""

# Run validation
if ! python3 "$VALIDATOR"; then
    echo ""
    echo "❌ Pre-push validation FAILED"
    echo "Push BLOCKED - fix errors and try again"
    echo ""
    echo "Bypass (NOT RECOMMENDED): git push --no-verify"
    echo ""
    exit 1
fi

echo ""
echo "✅ Pre-push validation PASSED"

# Post results to GitHub Issue (if Issue # found)
echo ""
echo "📋 Posting results to GitHub Issue..."
python3 "$REPORTER" || true  # Don't block on reporter failure

echo ""
echo "✅ Push allowed"
echo ""

exit 0
EOF

    chmod +x "$PRE_PUSH_HOOK"
    log_success "Pre-push hook installed: $PRE_PUSH_HOOK"
}

make_scripts_executable() {
    log_info "Making scripts executable..."
    chmod +x "$VALIDATOR_SCRIPT"
    chmod +x "$REPORTER_SCRIPT"
    log_success "Scripts are executable"
}

verify_installation() {
    log_info "Verifying installation..."

    if [ ! -x "$PRE_PUSH_HOOK" ]; then
        log_error "Pre-push hook is not executable"
        exit 1
    fi

    if [ ! -x "$VALIDATOR_SCRIPT" ]; then
        log_error "Validator script is not executable"
        exit 1
    fi

    if [ ! -x "$REPORTER_SCRIPT" ]; then
        log_error "Reporter script is not executable"
        exit 1
    fi

    log_success "All hooks and scripts are executable"
}

print_summary() {
    echo ""
    echo "=========================================="
    echo "TMWS Git Hooks Installation Complete"
    echo "=========================================="
    echo ""
    echo "✅ Pre-push hook installed"
    echo "✅ Validator script configured"
    echo "✅ Reporter script configured"
    echo ""
    echo "What happens on 'git push':"
    echo "  1. pytest runs (unit + integration)"
    echo "  2. mypy runs (type checking)"
    echo "  3. bandit runs (security scan)"
    echo "  4. Results posted to GitHub Issue (if Issue # in commit)"
    echo "  5. Push proceeds only if all pass"
    echo ""
    echo "Skip validation (NOT RECOMMENDED):"
    echo "  git push --no-verify"
    echo ""
    echo "Skip specific checks:"
    echo "  SKIP_TESTS=1 git push         # Skip pytest"
    echo "  SKIP_TYPECHECK=1 git push     # Skip mypy"
    echo "  SKIP_SECURITY=1 git push      # Skip bandit"
    echo ""
    echo "Test the hook manually:"
    echo "  python3 scripts/git-hooks/pre-push-validator.py"
    echo ""
    echo "=========================================="
}

# ============================================
# Main Execution
# ============================================

main() {
    log_info "Starting TMWS Git Hooks installation..."
    echo ""

    check_git_repo
    check_python
    check_scripts_exist

    backup_existing_hook
    create_pre_push_hook
    make_scripts_executable
    verify_installation

    print_summary
}

main "$@"
