name: Trinitas Quality Guardian CI
# Comprehensive CI/CD pipeline for quality assurance
# Orchestrated by Hera for optimal parallel execution

on:
  push:
    branches: [main, develop, release/*]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Enable debug mode'
        required: false
        default: false

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  CACHE_VERSION: v1

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  # ============================================
  # Artemis: Code Quality Analysis
  # ============================================
  code-quality:
    name: "Artemis: Code Quality Check"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
            ~/.ruff_cache
          key: ${{ runner.os }}-pip-${{ env.CACHE_VERSION }}-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.CACHE_VERSION }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov

      - name: Run Ruff Linter
        id: ruff
        run: |
          echo "::group::Ruff Lint Results"
          ruff check . --output-format github
          echo "::endgroup::"
        continue-on-error: true

      - name: Run Ruff Formatter Check
        id: ruff-format
        run: |
          echo "::group::Ruff Format Check"
          ruff format --check .
          echo "::endgroup::"
        continue-on-error: true

      - name: Code Complexity Analysis
        run: |
          echo "::group::Complexity Analysis"
          ruff check . --select C90 --output-format text
          echo "::endgroup::"
        continue-on-error: true

      - name: Generate Quality Report
        if: always()
        run: |
          echo "## Artemis Code Quality Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.ruff.outcome }}" == "success" ]]; then
            echo "✅ **Linting**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Linting**: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ steps.ruff-format.outcome }}" == "success" ]]; then
            echo "✅ **Formatting**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Formatting**: Failed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Fail if Quality Checks Failed
        if: steps.ruff.outcome == 'failure' || steps.ruff-format.outcome == 'failure'
        run: exit 1

  # ============================================
  # Hestia: Security Scanning
  # ============================================
  security-scan:
    name: "Hestia: Security Analysis"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Security Tools
        run: |
          pip install bandit safety pip-audit

      - name: Run Bandit Security Scan
        id: bandit
        run: |
          echo "::group::Bandit Security Scan"
          bandit -r . -ll -f json -o bandit-report.json || true
          bandit -r . -ll -f txt
          echo "::endgroup::"
        continue-on-error: true

      - name: Check Dependencies for Vulnerabilities
        id: safety
        run: |
          echo "::group::Dependency Vulnerability Check"
          pip-audit --desc || true
          echo "::endgroup::"
        continue-on-error: true

      - name: Secret Detection
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
        continue-on-error: true

      - name: Generate Security Report
        if: always()
        run: |
          echo "## Hestia Security Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🔒 Security scan completed" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.bandit.outcome }}" == "success" ]]; then
            echo "✅ **Code Security**: No issues found" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Code Security**: Issues detected (see logs)" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ steps.safety.outcome }}" == "success" ]]; then
            echo "✅ **Dependencies**: Secure" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Dependencies**: Vulnerabilities found" >> $GITHUB_STEP_SUMMARY
          fi

  # ============================================
  # Artemis: Test Execution & Coverage
  # ============================================
  test-suite:
    name: "Artemis: Test Suite"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [code-quality]

    strategy:
      matrix:
        python-version: ['3.11', '3.12']
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pytest pytest-cov pytest-xdist
          pip install -e . || true

      - name: Run Unit Tests
        id: unit-tests
        run: |
          echo "::group::Unit Tests"
          pytest tests/unit -v --cov=src --cov-report=term-missing --cov-report=xml --junit-xml=unit-results.xml -m "not integration and not e2e" || true
          echo "::endgroup::"
        continue-on-error: true

      - name: Run Integration Tests
        id: integration-tests
        if: success() || failure()
        run: |
          echo "::group::Integration Tests"
          pytest tests/integration -v --junit-xml=integration-results.xml -m integration || true
          echo "::endgroup::"
        continue-on-error: true

      - name: Upload Coverage Reports
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

      - name: Generate Test Report
        if: always()
        run: |
          echo "## Test Results (Python ${{ matrix.python-version }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.unit-tests.outcome }}" == "success" ]]; then
            echo "✅ **Unit Tests**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Unit Tests**: Failed" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ steps.integration-tests.outcome }}" == "success" ]]; then
            echo "✅ **Integration Tests**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Integration Tests**: Failed" >> $GITHUB_STEP_SUMMARY
          fi

  # ============================================
  # Muses: Documentation Check
  # ============================================
  documentation:
    name: "Muses: Documentation Quality"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Documentation Tools
        run: |
          npm install -g markdownlint-cli

      - name: Lint Markdown Files
        id: markdown-lint
        run: |
          echo "::group::Markdown Linting"
          markdownlint '**/*.md' --ignore node_modules || true
          echo "::endgroup::"
        continue-on-error: true

      - name: Check README Exists
        id: readme-check
        run: |
          if [[ -f "README.md" ]]; then
            echo "✅ README.md exists" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ README.md is missing" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Generate Documentation Report
        if: always()
        run: |
          echo "## Muses Documentation Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📚 Documentation check completed" >> $GITHUB_STEP_SUMMARY

  # ============================================
  # Athena: Final Integration & Reporting
  # ============================================
  quality-gate:
    name: "Athena: Quality Gate"
    runs-on: ubuntu-latest
    needs: [code-quality, security-scan, test-suite, documentation]
    if: always()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Evaluate Quality Gate
        id: gate
        run: |
          echo "## Athena Quality Gate Decision" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Check all job statuses
          CODE_QUALITY="${{ needs.code-quality.result }}"
          SECURITY="${{ needs.security-scan.result }}"
          TESTS="${{ needs.test-suite.result }}"
          DOCS="${{ needs.documentation.result }}"

          echo "### Job Results:" >> $GITHUB_STEP_SUMMARY
          echo "- Code Quality: $CODE_QUALITY" >> $GITHUB_STEP_SUMMARY
          echo "- Security: $SECURITY" >> $GITHUB_STEP_SUMMARY
          echo "- Tests: $TESTS" >> $GITHUB_STEP_SUMMARY
          echo "- Documentation: $DOCS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Determine overall status
          if [[ "$CODE_QUALITY" == "success" && "$TESTS" == "success" ]]; then
            echo "✅ **Quality Gate: PASSED**" >> $GITHUB_STEP_SUMMARY
            echo "The code meets Trinitas quality standards." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Quality Gate: FAILED**" >> $GITHUB_STEP_SUMMARY
            echo "The code does not meet minimum quality requirements." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Post PR Comment (if PR)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const body = `## Trinitas Quality Guardian Report

            **Athena's Assessment**: Your code has been reviewed by the Trinitas Quality Guardian.

            | Check | Status |
            |-------|--------|
            | Code Quality (Artemis) | ${{ needs.code-quality.result == 'success' && '✅' || '❌' }} |
            | Security (Hestia) | ${{ needs.security-scan.result == 'success' && '✅' || '⚠️' }} |
            | Tests (Artemis) | ${{ needs.test-suite.result == 'success' && '✅' || '❌' }} |
            | Documentation (Muses) | ${{ needs.documentation.result == 'success' && '✅' || '⚠️' }} |

            For detailed results, check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
        continue-on-error: true