// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/orchestrator.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoverToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverToolsRequest) Reset() {
	*x = DiscoverToolsRequest{}
	mi := &file_api_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverToolsRequest) ProtoMessage() {}

func (x *DiscoverToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverToolsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverToolsRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverToolsRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DiscoverToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverToolsResponse) Reset() {
	*x = DiscoverToolsResponse{}
	mi := &file_api_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverToolsResponse) ProtoMessage() {}

func (x *DiscoverToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverToolsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverToolsResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *DiscoverToolsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToolRequest) Reset() {
	*x = GetToolRequest{}
	mi := &file_api_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToolRequest) ProtoMessage() {}

func (x *GetToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToolRequest.ProtoReflect.Descriptor instead.
func (*GetToolRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *GetToolRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`   // optional filter
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // required for security
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_api_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListToolsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_api_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *ListToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	SourcePath    string                 `protobuf:"bytes,4,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_api_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *Tool) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Tool) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *Tool) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Tool) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StartContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,2,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Volumes       []string               `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_api_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *StartContainerRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *StartContainerRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *StartContainerRequest) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type ContainerInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ToolId        string                 `protobuf:"bytes,2,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInstance) Reset() {
	*x = ContainerInstance{}
	mi := &file_api_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInstance) ProtoMessage() {}

func (x *ContainerInstance) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInstance.ProtoReflect.Descriptor instead.
func (*ContainerInstance) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerInstance) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerInstance) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ContainerInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerInstance) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type StopContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_api_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *StopContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_api_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *StopContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopContainerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetContainerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusRequest) Reset() {
	*x = GetContainerStatusRequest{}
	mi := &file_api_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusRequest) ProtoMessage() {}

func (x *GetContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *GetContainerStatusRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Stats         map[string]string      `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_api_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_api_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ContainerStatus) GetStats() map[string]string {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_api_orchestrator_proto protoreflect.FileDescriptor

const file_api_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x16api/orchestrator.proto\x12\forchestrator\",\n" +
	"\x14DiscoverToolsRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"b\n" +
	"\x15DiscoverToolsResponse\x12(\n" +
	"\x05tools\x18\x01 \x03(\v2\x12.orchestrator.ToolR\x05tools\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x0eGetToolRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"L\n" +
	"\x10ListToolsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"=\n" +
	"\x11ListToolsResponse\x12(\n" +
	"\x05tools\x18\x01 \x03(\v2\x12.orchestrator.ToolR\x05tools\"\x85\x02\n" +
	"\x04Tool\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1f\n" +
	"\vsource_path\x18\x04 \x01(\tR\n" +
	"sourcePath\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12<\n" +
	"\bmetadata\x18\x06 \x03(\v2 .orchestrator.Tool.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\x15StartContainerRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12V\n" +
	"\venvironment\x18\x02 \x03(\v24.orchestrator.StartContainerRequest.EnvironmentEntryR\venvironment\x12\x18\n" +
	"\avolumes\x18\x03 \x03(\tR\avolumes\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x11ContainerInstance\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\atool_id\x18\x02 \x01(\tR\x06toolId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\"9\n" +
	"\x14StopContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"K\n" +
	"\x15StopContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x19GetContainerStatusRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xed\x01\n" +
	"\x0fContainerStatus\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12>\n" +
	"\x05stats\x18\x04 \x03(\v2(.orchestrator.ContainerStatus.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8a\x04\n" +
	"\x13OrchestratorService\x12X\n" +
	"\rDiscoverTools\x12\".orchestrator.DiscoverToolsRequest\x1a#.orchestrator.DiscoverToolsResponse\x12;\n" +
	"\aGetTool\x12\x1c.orchestrator.GetToolRequest\x1a\x12.orchestrator.Tool\x12L\n" +
	"\tListTools\x12\x1e.orchestrator.ListToolsRequest\x1a\x1f.orchestrator.ListToolsResponse\x12V\n" +
	"\x0eStartContainer\x12#.orchestrator.StartContainerRequest\x1a\x1f.orchestrator.ContainerInstance\x12X\n" +
	"\rStopContainer\x12\".orchestrator.StopContainerRequest\x1a#.orchestrator.StopContainerResponse\x12\\\n" +
	"\x12GetContainerStatus\x12'.orchestrator.GetContainerStatusRequest\x1a\x1d.orchestrator.ContainerStatusB.Z,github.com/apto-as/tmws/src/orchestrator/apib\x06proto3"

var (
	file_api_orchestrator_proto_rawDescOnce sync.Once
	file_api_orchestrator_proto_rawDescData []byte
)

func file_api_orchestrator_proto_rawDescGZIP() []byte {
	file_api_orchestrator_proto_rawDescOnce.Do(func() {
		file_api_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orchestrator_proto_rawDesc), len(file_api_orchestrator_proto_rawDesc)))
	})
	return file_api_orchestrator_proto_rawDescData
}

var file_api_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_orchestrator_proto_goTypes = []any{
	(*DiscoverToolsRequest)(nil),      // 0: orchestrator.DiscoverToolsRequest
	(*DiscoverToolsResponse)(nil),     // 1: orchestrator.DiscoverToolsResponse
	(*GetToolRequest)(nil),            // 2: orchestrator.GetToolRequest
	(*ListToolsRequest)(nil),          // 3: orchestrator.ListToolsRequest
	(*ListToolsResponse)(nil),         // 4: orchestrator.ListToolsResponse
	(*Tool)(nil),                      // 5: orchestrator.Tool
	(*StartContainerRequest)(nil),     // 6: orchestrator.StartContainerRequest
	(*ContainerInstance)(nil),         // 7: orchestrator.ContainerInstance
	(*StopContainerRequest)(nil),      // 8: orchestrator.StopContainerRequest
	(*StopContainerResponse)(nil),     // 9: orchestrator.StopContainerResponse
	(*GetContainerStatusRequest)(nil), // 10: orchestrator.GetContainerStatusRequest
	(*ContainerStatus)(nil),           // 11: orchestrator.ContainerStatus
	nil,                               // 12: orchestrator.Tool.MetadataEntry
	nil,                               // 13: orchestrator.StartContainerRequest.EnvironmentEntry
	nil,                               // 14: orchestrator.ContainerStatus.StatsEntry
}
var file_api_orchestrator_proto_depIdxs = []int32{
	5,  // 0: orchestrator.DiscoverToolsResponse.tools:type_name -> orchestrator.Tool
	5,  // 1: orchestrator.ListToolsResponse.tools:type_name -> orchestrator.Tool
	12, // 2: orchestrator.Tool.metadata:type_name -> orchestrator.Tool.MetadataEntry
	13, // 3: orchestrator.StartContainerRequest.environment:type_name -> orchestrator.StartContainerRequest.EnvironmentEntry
	14, // 4: orchestrator.ContainerStatus.stats:type_name -> orchestrator.ContainerStatus.StatsEntry
	0,  // 5: orchestrator.OrchestratorService.DiscoverTools:input_type -> orchestrator.DiscoverToolsRequest
	2,  // 6: orchestrator.OrchestratorService.GetTool:input_type -> orchestrator.GetToolRequest
	3,  // 7: orchestrator.OrchestratorService.ListTools:input_type -> orchestrator.ListToolsRequest
	6,  // 8: orchestrator.OrchestratorService.StartContainer:input_type -> orchestrator.StartContainerRequest
	8,  // 9: orchestrator.OrchestratorService.StopContainer:input_type -> orchestrator.StopContainerRequest
	10, // 10: orchestrator.OrchestratorService.GetContainerStatus:input_type -> orchestrator.GetContainerStatusRequest
	1,  // 11: orchestrator.OrchestratorService.DiscoverTools:output_type -> orchestrator.DiscoverToolsResponse
	5,  // 12: orchestrator.OrchestratorService.GetTool:output_type -> orchestrator.Tool
	4,  // 13: orchestrator.OrchestratorService.ListTools:output_type -> orchestrator.ListToolsResponse
	7,  // 14: orchestrator.OrchestratorService.StartContainer:output_type -> orchestrator.ContainerInstance
	9,  // 15: orchestrator.OrchestratorService.StopContainer:output_type -> orchestrator.StopContainerResponse
	11, // 16: orchestrator.OrchestratorService.GetContainerStatus:output_type -> orchestrator.ContainerStatus
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_orchestrator_proto_init() }
func file_api_orchestrator_proto_init() {
	if File_api_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orchestrator_proto_rawDesc), len(file_api_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orchestrator_proto_goTypes,
		DependencyIndexes: file_api_orchestrator_proto_depIdxs,
		MessageInfos:      file_api_orchestrator_proto_msgTypes,
	}.Build()
	File_api_orchestrator_proto = out.File
	file_api_orchestrator_proto_goTypes = nil
	file_api_orchestrator_proto_depIdxs = nil
}
