"""GenAI Toolbox Integration Schema

Revision ID: 005_genai_toolbox_integration
Revises: 004_multi_instance
Create Date: 2025-09-22 (Generated by Athena & Hera)

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "005"
down_revision = "004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add GenAI Toolbox integration tables."""

    # GenAI Toolbox統合登録テーブル
    op.create_table(
        "genai_toolbox_integrations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tool_name", sa.String(100), nullable=False, index=True),
        sa.Column("tool_type", sa.String(50), nullable=False),
        sa.Column("binary_path", sa.String(500), nullable=False),
        sa.Column("go_process_id", sa.String(100), nullable=True),
        sa.Column("python_bridge_id", sa.String(100), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, default="inactive"),
        sa.Column("config", postgresql.JSONB, nullable=True),
        sa.Column("metadata", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.TIMESTAMP, nullable=False, server_default=sa.text("NOW()")),
        sa.Column("updated_at", sa.TIMESTAMP, nullable=False, server_default=sa.text("NOW()")),
        sa.UniqueConstraint("tool_name", name="uq_genai_tool_name"),
    )

    # ツール間通信テーブル
    op.create_table(
        "inter_tool_messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("from_tool", sa.String(100), nullable=False, index=True),
        sa.Column("to_tool", sa.String(100), nullable=False, index=True),
        sa.Column("message_type", sa.String(50), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("status", sa.String(20), nullable=False, default="pending"),
        sa.Column("processed_at", sa.TIMESTAMP, nullable=True),
        sa.Column("error_message", sa.Text, nullable=True),
        sa.Column("created_at", sa.TIMESTAMP, nullable=False, server_default=sa.text("NOW()")),
        sa.Index("idx_inter_tool_messages_status", "status"),
        sa.Index("idx_inter_tool_messages_created", "created_at"),
    )

    # GenAI実行履歴テーブル
    op.create_table(
        "genai_execution_history",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tool_name", sa.String(100), nullable=False, index=True),
        sa.Column("prompt", sa.Text, nullable=False),
        sa.Column("config_used", postgresql.JSONB, nullable=True),
        sa.Column("result", postgresql.JSONB, nullable=True),
        sa.Column("execution_time_ms", sa.Integer, nullable=True),
        sa.Column("token_usage", postgresql.JSONB, nullable=True),
        sa.Column("cost_estimate", sa.Numeric(10, 4), nullable=True),
        sa.Column("agent_id", sa.String(100), nullable=False),
        sa.Column("instance_id", sa.String(100), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, default="completed"),
        sa.Column("error_details", sa.Text, nullable=True),
        sa.Column("created_at", sa.TIMESTAMP, nullable=False, server_default=sa.text("NOW()")),
        sa.Index("idx_genai_execution_tool", "tool_name"),
        sa.Index("idx_genai_execution_agent", "agent_id"),
        sa.Index("idx_genai_execution_created", "created_at"),
    )

    # プロセス監視テーブル
    op.create_table(
        "genai_process_monitoring",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("tool_name", sa.String(100), nullable=False, index=True),
        sa.Column("process_id", sa.String(100), nullable=False),
        sa.Column("binary_path", sa.String(500), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP, nullable=False),
        sa.Column("last_heartbeat", sa.TIMESTAMP, nullable=False),
        sa.Column("status", sa.String(20), nullable=False, default="starting"),
        sa.Column("memory_usage_mb", sa.Integer, nullable=True),
        sa.Column("cpu_usage_percent", sa.Numeric(5, 2), nullable=True),
        sa.Column("request_count", sa.BigInteger, nullable=False, default=0),
        sa.Column("error_count", sa.BigInteger, nullable=False, default=0),
        sa.Column("host_info", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.TIMESTAMP, nullable=False, server_default=sa.text("NOW()")),
        sa.Index("idx_genai_process_status", "status"),
        sa.Index("idx_genai_process_heartbeat", "last_heartbeat"),
    )

    # shared_memoriesテーブルにGenAI関連のメタデータカラム追加
    op.add_column("shared_memories", sa.Column("genai_source_tool", sa.String(100), nullable=True))
    op.add_column(
        "shared_memories",
        sa.Column("genai_execution_id", postgresql.UUID(as_uuid=True), nullable=True),
    )

    # インデックス追加
    op.create_index("idx_shared_memories_genai_tool", "shared_memories", ["genai_source_tool"])

    # 外部キー制約
    op.create_foreign_key(
        "fk_memories_genai_execution",
        "shared_memories",
        "genai_execution_history",
        ["genai_execution_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # PostgreSQL通知トリガー (GenAI Toolbox用)
    op.execute("""
        CREATE OR REPLACE FUNCTION notify_genai_tool_changes()
        RETURNS TRIGGER AS $$
        BEGIN
            PERFORM pg_notify(
                'genai_tool_changes',
                json_build_object(
                    'tool_name', COALESCE(NEW.tool_name, OLD.tool_name),
                    'status', COALESCE(NEW.status, 'deleted'),
                    'change_type', TG_OP
                )::text
            );
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trigger_genai_tool_changes
        AFTER INSERT OR UPDATE OR DELETE ON genai_toolbox_integrations
        FOR EACH ROW EXECUTE FUNCTION notify_genai_tool_changes();
    """)


def downgrade() -> None:
    """Remove GenAI Toolbox integration tables."""

    # トリガーとファンクション削除
    op.execute("DROP TRIGGER IF EXISTS trigger_genai_tool_changes ON genai_toolbox_integrations;")
    op.execute("DROP FUNCTION IF EXISTS notify_genai_tool_changes();")

    # 外部キー制約削除
    op.drop_constraint("fk_memories_genai_execution", "shared_memories", type_="foreignkey")

    # インデックス削除
    op.drop_index("idx_shared_memories_genai_tool", table_name="shared_memories")

    # カラム削除
    op.drop_column("shared_memories", "genai_execution_id")
    op.drop_column("shared_memories", "genai_source_tool")

    # テーブル削除
    op.drop_table("genai_process_monitoring")
    op.drop_table("genai_execution_history")
    op.drop_table("inter_tool_messages")
    op.drop_table("genai_toolbox_integrations")
