"""Add conversation_logs and conversation_sessions tables for SubAgent tracking

Revision ID: 059051494a66
Revises: 6a5bcf8438bd
Create Date: 2025-12-13 12:20:24.953660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059051494a66'
down_revision: Union[str, Sequence[str], None] = '6a5bcf8438bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_logs',
    sa.Column('agent_id', sa.Text(), nullable=False, comment="Agent identifier (e.g., 'artemis-optimizer', 'hera-strategist')"),
    sa.Column('session_id', sa.Text(), nullable=False, comment='Parent session ID for grouping related conversations'),
    sa.Column('role', sa.Text(), nullable=False, comment="Message role: 'user' or 'assistant'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('parent_message_id', sa.String(length=36), nullable=True, comment='Parent message ID for threaded conversations'),
    sa.Column('context_metadata', sa.JSON(), nullable=False, comment='Additional context: task_type, phase, success_status, etc.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Message timestamp'),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='Response time in milliseconds (for assistant messages)'),
    sa.Column('pattern_extracted', sa.Boolean(), nullable=False, comment='Whether patterns have been extracted from this conversation'),
    sa.Column('skill_candidate', sa.Boolean(), nullable=False, comment='Whether this conversation is a candidate for Skill generation'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['conversation_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_agent_session', 'conversation_logs', ['agent_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_agent_id'), 'conversation_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_pattern_extracted'), 'conversation_logs', ['pattern_extracted'], unique=False)
    op.create_index(op.f('ix_conversation_logs_session_id'), 'conversation_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_skill_candidate'), 'conversation_logs', ['skill_candidate'], unique=False)
    op.create_index(op.f('ix_conversation_logs_timestamp'), 'conversation_logs', ['timestamp'], unique=False)
    op.create_index('ix_conversation_pattern_flags', 'conversation_logs', ['pattern_extracted', 'skill_candidate'], unique=False)
    op.create_index('ix_conversation_timestamp', 'conversation_logs', ['timestamp'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('session_id', sa.Text(), nullable=False, comment='Unique session identifier'),
    sa.Column('agent_id', sa.Text(), nullable=False, comment='Primary agent for this session'),
    sa.Column('task_type', sa.Text(), nullable=True, comment="Type of task: 'optimization', 'security_audit', 'strategic_planning', etc."),
    sa.Column('phase', sa.Text(), nullable=True, comment="Trinitas phase: 'phase_1_strategic', 'phase_2_implementation', etc."),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True, comment='Whether the session completed successfully'),
    sa.Column('outcome', sa.JSON(), nullable=False, comment='Session outcome data: results, metrics, artifacts'),
    sa.Column('learning_patterns', sa.JSON(), nullable=False, comment='List of learning pattern IDs extracted from this session'),
    sa.Column('skills_generated', sa.JSON(), nullable=False, comment='List of skill IDs auto-generated from this session'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_agent_id'), 'conversation_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_completed_at'), 'conversation_sessions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_session_id'), 'conversation_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_conversation_sessions_started_at'), 'conversation_sessions', ['started_at'], unique=False)
    op.create_index('ix_session_agent_started', 'conversation_sessions', ['agent_id', 'started_at'], unique=False)
    op.create_index('ix_session_success', 'conversation_sessions', ['success', 'completed_at'], unique=False)
    op.create_index('ix_session_task_type', 'conversation_sessions', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_task_type', table_name='conversation_sessions')
    op.drop_index('ix_session_success', table_name='conversation_sessions')
    op.drop_index('ix_session_agent_started', table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_started_at'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_session_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_completed_at'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_agent_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('ix_conversation_timestamp', table_name='conversation_logs')
    op.drop_index('ix_conversation_pattern_flags', table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_timestamp'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_skill_candidate'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_session_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_pattern_extracted'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_agent_id'), table_name='conversation_logs')
    op.drop_index('ix_conversation_agent_session', table_name='conversation_logs')
    op.drop_table('conversation_logs')
    # ### end Alembic commands ###
