"""initial_schema_sqlite_chromadb

Revision ID: 43ffdc09701d
Revises: 
Create Date: 2025-10-26 23:34:48.811407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ffdc09701d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_namespaces',
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_agent_id', sa.Text(), nullable=True),
    sa.Column('admin_agents', sa.JSON(), nullable=False),
    sa.Column('member_agents', sa.JSON(), nullable=False),
    sa.Column('default_access_level', sa.Enum('private', 'team', 'shared', 'public', 'system', name='accesslevel'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_namespaces_is_active'), 'agent_namespaces', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_namespaces_namespace'), 'agent_namespaces', ['namespace'], unique=True)
    op.create_table('agent_teams',
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('leader_agent_id', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('shared_namespace', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_teams_is_active'), 'agent_teams', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_teams_team_id'), 'agent_teams', ['team_id'], unique=True)
    op.create_table('agents',
    sa.Column('agent_id', sa.Text(), nullable=False, comment="Unique identifier for the agent (e.g., 'claude-3', 'gpt-4', 'athena-conductor')"),
    sa.Column('display_name', sa.Text(), nullable=False, comment='Human-readable name for the agent'),
    sa.Column('organization_id', sa.Text(), nullable=True, comment='Organization or project identifier'),
    sa.Column('namespace', sa.Text(), nullable=False, comment='Namespace for memory isolation'),
    sa.Column('agent_type', sa.Text(), nullable=True, comment="Type of agent (e.g., 'language_model', 'task_executor', 'coordinator')"),
    sa.Column('capabilities', sa.JSON(), nullable=False, comment='Dynamic capabilities and features'),
    sa.Column('config', sa.JSON(), nullable=False, comment='Agent-specific configuration'),
    sa.Column('default_access_level', sa.Enum('private', 'team', 'shared', 'public', 'system', name='accesslevel'), nullable=False, comment="Default access level for agent's memories"),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'deprecated', name='agentstatus'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False, comment='Health score (0.0 - 1.0)'),
    sa.Column('total_memories', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('successful_tasks', sa.Integer(), nullable=False),
    sa.Column('average_response_time_ms', sa.Float(), nullable=True),
    sa.Column('api_key_hash', sa.Text(), nullable=True, comment='Hashed API key for agent authentication'),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_org_namespace', 'agents', ['organization_id', 'namespace'], unique=False)
    op.create_index('ix_agent_status_active', 'agents', ['status', 'last_active_at'], unique=False)
    op.create_index('ix_agent_type_status', 'agents', ['agent_type', 'status'], unique=False)
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_last_active_at'), 'agents', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_agents_namespace'), 'agents', ['namespace'], unique=False)
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('api_audit_log',
    sa.Column('endpoint', sa.String(length=255), nullable=False, comment='API endpoint path'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP method (GET, POST, PUT, DELETE, PATCH)'),
    sa.Column('request_body', sa.JSON(), nullable=True, comment='Request body in JSON format'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('response_body', sa.JSON(), nullable=True, comment='Response body in JSON format'),
    sa.Column('user_id', sa.String(length=100), nullable=True, comment='User identifier who made the request'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request processing duration in milliseconds'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH')", name='chk_method'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_audit_log_created_at', 'api_audit_log', ['created_at'], unique=False)
    op.create_index('idx_api_audit_log_endpoint', 'api_audit_log', ['endpoint'], unique=False)
    op.create_index('idx_api_audit_log_user_id', 'api_audit_log', ['user_id'], unique=False)
    op.create_table('learning_patterns',
    sa.Column('pattern_name', sa.String(length=255), nullable=False, comment='Pattern name identifier'),
    sa.Column('agent_id', sa.Text(), nullable=True, comment='Owner agent identifier (null for system patterns)'),
    sa.Column('namespace', sa.String(length=100), server_default=sa.text("'default'"), nullable=False, comment='Pattern namespace for organization and isolation'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='Pattern category classification'),
    sa.Column('subcategory', sa.String(length=100), nullable=True, comment='Pattern subcategory for fine-grained classification'),
    sa.Column('access_level', sa.String(length=20), server_default=sa.text("'private'"), nullable=False, comment='Access level: private, shared, public, system'),
    sa.Column('pattern_data', sa.JSON(), nullable=False, comment='Pattern data structure with enhanced schema'),
    sa.Column('version', sa.String(length=50), server_default=sa.text("'1.0.0'"), nullable=False, comment='Pattern version for evolution tracking'),
    sa.Column('parent_pattern_id', sa.String(length=36), nullable=True, comment='Parent pattern for versioning hierarchy'),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total usage count across all agents'),
    sa.Column('agent_usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Usage count by the owner agent'),
    sa.Column('success_rate', sa.Float(), server_default=sa.text('(0.0)'), nullable=False, comment='Overall success rate (0.0-1.0)'),
    sa.Column('agent_success_rate', sa.Float(), server_default=sa.text('(0.0)'), nullable=False, comment='Success rate for the owner agent (0.0-1.0)'),
    sa.Column('avg_execution_time', sa.Float(), nullable=True, comment='Average execution time in seconds'),
    sa.Column('complexity_score', sa.Float(), nullable=True, comment='Pattern complexity score for optimization'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last usage timestamp'),
    sa.Column('last_agent_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last usage by owner agent'),
    sa.Column('shared_with_agents', sa.JSON(), nullable=True, comment='List of agent IDs with shared access'),
    sa.Column('learning_weight', sa.Float(), server_default=sa.text('(1.0)'), nullable=False, comment='Weight for learning algorithms'),
    sa.Column('confidence_score', sa.Float(), server_default=sa.text('(0.5)'), nullable=False, comment='Confidence in pattern effectiveness'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.CheckConstraint("access_level IN ('private', 'shared', 'public', 'system')", name='ck_learning_patterns_access_level'),
    sa.CheckConstraint('agent_success_rate >= 0.0 AND agent_success_rate <= 1.0', name='ck_learning_patterns_agent_success_rate'),
    sa.CheckConstraint('agent_usage_count >= 0', name='ck_learning_patterns_agent_usage_count'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_learning_patterns_confidence_score'),
    sa.CheckConstraint('success_rate >= 0.0 AND success_rate <= 1.0', name='ck_learning_patterns_success_rate'),
    sa.CheckConstraint('usage_count >= 0', name='ck_learning_patterns_usage_count'),
    sa.ForeignKeyConstraint(['parent_pattern_id'], ['learning_patterns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_name', 'namespace', 'agent_id', name='uq_learning_patterns_name_namespace_agent')
    )
    op.create_index('idx_learning_patterns_agent_namespace', 'learning_patterns', ['agent_id', 'namespace'], unique=False)
    op.create_index('idx_learning_patterns_category_access', 'learning_patterns', ['category', 'access_level'], unique=False)
    op.create_index('idx_learning_patterns_last_used', 'learning_patterns', ['last_used_at'], unique=False)
    op.create_index('idx_learning_patterns_usage', 'learning_patterns', ['usage_count'], unique=False)
    op.create_index(op.f('ix_learning_patterns_agent_id'), 'learning_patterns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_learning_patterns_category'), 'learning_patterns', ['category'], unique=False)
    op.create_index(op.f('ix_learning_patterns_namespace'), 'learning_patterns', ['namespace'], unique=False)
    op.create_table('memories',
    sa.Column('content', sa.Text(), nullable=False, comment='The actual memory content'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Auto-generated summary for long content'),
    sa.Column('agent_id', sa.Text(), nullable=False, comment='Owner agent identifier'),
    sa.Column('namespace', sa.Text(), nullable=False, comment='Namespace for memory isolation'),
    sa.Column('embedding_model', sa.Text(), nullable=False, comment="Embedding model used in Chroma: 'zylonai/multilingual-e5-large' (1024-dim)"),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False, comment='Embedding dimension for Chroma vectors'),
    sa.Column('access_level', sa.Enum('private', 'team', 'shared', 'public', 'system', name='accesslevel'), nullable=False, comment='Access level for this memory'),
    sa.Column('shared_with_agents', sa.JSON(), nullable=False, comment='List of agent_ids with explicit access'),
    sa.Column('context', sa.JSON(), nullable=False, comment='Flexible context metadata'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='Tags for categorization'),
    sa.Column('source_url', sa.Text(), nullable=True, comment='Source URL if applicable'),
    sa.Column('importance_score', sa.Float(), nullable=False, comment='Importance score (0.0 - 1.0)'),
    sa.Column('relevance_score', sa.Float(), nullable=False, comment='Current relevance score (0.0 - 1.0)'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='Number of times accessed'),
    sa.Column('learning_weight', sa.Float(), nullable=False, comment='Weight for learning algorithms'),
    sa.Column('pattern_ids', sa.JSON(), nullable=False, comment='Associated learning pattern IDs'),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True, comment='Last access timestamp'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Expiration timestamp for temporary memories'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version for optimistic locking'),
    sa.Column('parent_memory_id', sa.String(length=36), nullable=True, comment='Parent memory for hierarchical organization'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.ForeignKeyConstraint(['parent_memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_access_level'), 'memories', ['access_level'], unique=False)
    op.create_index(op.f('ix_memories_accessed_at'), 'memories', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_memories_agent_id'), 'memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memories_expires_at'), 'memories', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memories_namespace'), 'memories', ['namespace'], unique=False)
    op.create_index('ix_memory_access_level', 'memories', ['access_level', 'agent_id'], unique=False)
    op.create_index('ix_memory_accessed', 'memories', ['accessed_at', 'access_count'], unique=False)
    op.create_index('ix_memory_agent_namespace', 'memories', ['agent_id', 'namespace'], unique=False)
    op.create_index('ix_memory_expires', 'memories', ['expires_at'], unique=False)
    op.create_index('ix_memory_importance', 'memories', ['importance_score', 'relevance_score'], unique=False)
    op.create_table('memory_patterns',
    sa.Column('pattern_type', sa.Text(), nullable=False, comment='Type: sequence, correlation, cluster, etc.'),
    sa.Column('agent_id', sa.Text(), nullable=False, comment='Agent who owns this pattern'),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=False, comment='The actual pattern data'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score (0.0 - 1.0)'),
    sa.Column('frequency', sa.Integer(), nullable=False, comment='Occurrence frequency'),
    sa.Column('memory_ids', sa.JSON(), nullable=False, comment='Associated memory IDs'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_patterns_agent_id'), 'memory_patterns', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memory_patterns_is_active'), 'memory_patterns', ['is_active'], unique=False)
    op.create_index(op.f('ix_memory_patterns_namespace'), 'memory_patterns', ['namespace'], unique=False)
    op.create_index('ix_pattern_agent_type', 'memory_patterns', ['agent_id', 'pattern_type'], unique=False)
    op.create_index('ix_pattern_confidence', 'memory_patterns', ['confidence', 'frequency'], unique=False)
    op.create_table('personas',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('athena', 'artemis', 'hestia', 'bellona', 'seshat', name='personatype'), nullable=False),
    sa.Column('role', sa.Enum('strategist', 'optimizer', 'auditor', 'coordinator', 'documenter', name='personarole'), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('successful_tasks', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persona_active_last_active', 'personas', ['is_active', 'last_active_at'], unique=False)
    op.create_index('ix_persona_role_active', 'personas', ['role', 'is_active'], unique=False)
    op.create_index('ix_persona_type_active', 'personas', ['type', 'is_active'], unique=False)
    op.create_index(op.f('ix_personas_is_active'), 'personas', ['is_active'], unique=False)
    op.create_index(op.f('ix_personas_last_active_at'), 'personas', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=True)
    op.create_index(op.f('ix_personas_role'), 'personas', ['role'], unique=False)
    op.create_index(op.f('ix_personas_type'), 'personas', ['type'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('event_hash', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_client_ip', 'security_audit_logs', ['client_ip'], unique=False)
    op.create_index('idx_audit_logs_event_type_timestamp', 'security_audit_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_audit_logs_timestamp_severity', 'security_audit_logs', ['timestamp', 'severity'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_client_ip'), 'security_audit_logs', ['client_ip'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_hash'), 'security_audit_logs', ['event_hash'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_risk_score'), 'security_audit_logs', ['risk_score'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_session_id'), 'security_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_severity'), 'security_audit_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_timestamp'), 'security_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    op.create_table('task_templates',
    sa.Column('template_id', sa.Text(), nullable=False, comment='Unique template identifier'),
    sa.Column('name', sa.Text(), nullable=False, comment='Human-readable template name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Template description and usage guidelines'),
    sa.Column('title_template', sa.Text(), nullable=False, comment='Template title with placeholders'),
    sa.Column('description_template', sa.Text(), nullable=False, comment='Template description with placeholders'),
    sa.Column('required_fields', sa.JSON(), nullable=False, comment='Required fields for template instantiation'),
    sa.Column('optional_fields', sa.JSON(), nullable=False, comment='Optional fields for template instantiation'),
    sa.Column('default_task_type', sa.Text(), nullable=False, comment='Default task type for instances'),
    sa.Column('default_priority', sa.Enum('low', 'medium', 'high', 'urgent', 'critical', name='taskpriority'), nullable=False, comment='Default priority for instances'),
    sa.Column('default_access_level', sa.Text(), nullable=False, comment='Default access level for instances'),
    sa.Column('default_config', sa.JSON(), nullable=False, comment='Default task configuration'),
    sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='Estimated duration in seconds for template instances'),
    sa.Column('namespace', sa.Text(), nullable=False, comment='Template namespace'),
    sa.Column('created_by', sa.Text(), nullable=True, comment='Agent ID of template creator'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether template is active and available'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Number of times template has been used'),
    sa.Column('success_rate', sa.Float(), nullable=False, comment='Success rate of tasks created from this template'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.CheckConstraint("default_access_level IN ('private', 'shared', 'public', 'system')", name='default_access_level_check'),
    sa.CheckConstraint('estimated_duration IS NULL OR estimated_duration > 0', name='estimated_duration_positive'),
    sa.CheckConstraint('success_rate >= 0.0 AND success_rate <= 1.0', name='success_rate_bounds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_templates_namespace', 'task_templates', ['namespace', 'is_active'], unique=False)
    op.create_index('idx_task_templates_success', 'task_templates', ['success_rate'], unique=False)
    op.create_index('idx_task_templates_usage', 'task_templates', ['usage_count'], unique=False)
    op.create_index(op.f('ix_task_templates_is_active'), 'task_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_task_templates_namespace'), 'task_templates', ['namespace'], unique=False)
    op.create_index(op.f('ix_task_templates_template_id'), 'task_templates', ['template_id'], unique=True)
    op.create_table('tasks',
    sa.Column('title', sa.Text(), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed task description'),
    sa.Column('task_type', sa.Text(), nullable=False, comment='Task type for categorization'),
    sa.Column('assigned_agent_id', sa.Text(), nullable=True, comment='Primary agent assigned to this task'),
    sa.Column('collaborating_agents', sa.JSON(), nullable=False, comment='Additional agents collaborating on this task'),
    sa.Column('namespace', sa.Text(), nullable=False, comment='Namespace for task isolation and organization'),
    sa.Column('access_level', sa.Text(), nullable=False, comment="Access level: 'private', 'shared', 'public', 'system'"),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', 'paused', name='taskstatus'), nullable=False, comment='Current task status'),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', 'critical', name='taskpriority'), nullable=False, comment='Task priority level'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True, comment='Scheduled execution time'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Task start time'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Task completion time'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Task due date'),
    sa.Column('dependencies', sa.JSON(), nullable=False, comment='List of task IDs that must complete before this task'),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True, comment='Parent task for hierarchical task structures'),
    sa.Column('workflow_id', sa.String(length=36), nullable=True, comment='Associated workflow ID'),
    sa.Column('task_config', sa.JSON(), nullable=False, comment='Task-specific configuration parameters'),
    sa.Column('input_data', sa.JSON(), nullable=False, comment='Input data for task execution'),
    sa.Column('output_data', sa.JSON(), nullable=False, comment='Output data from task execution'),
    sa.Column('progress_percentage', sa.Float(), nullable=False, comment='Task completion percentage (0.0 to 100.0)'),
    sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='Estimated duration in seconds'),
    sa.Column('actual_duration', sa.Integer(), nullable=True, comment='Actual duration in seconds'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum number of retry attempts'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if task failed'),
    sa.Column('error_details', sa.JSON(), nullable=False, comment='Detailed error information'),
    sa.Column('execution_log', sa.JSON(), nullable=False, comment='Execution log entries'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='User-defined tags for categorization'),
    sa.Column('context_tags', sa.JSON(), nullable=False, comment='Contextual tags for enhanced organization'),
    sa.Column('resource_requirements', sa.JSON(), nullable=False, comment='Required resources (CPU, memory, etc.)'),
    sa.Column('resource_usage', sa.JSON(), nullable=False, comment='Actual resource usage during execution'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Task execution quality score (0.0 to 10.0)'),
    sa.Column('success_criteria', sa.JSON(), nullable=False, comment='Criteria for determining task success'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.CheckConstraint("access_level IN ('private', 'shared', 'public', 'system')", name='access_level_check'),
    sa.CheckConstraint('LENGTH(description) >= 1', name='description_not_empty'),
    sa.CheckConstraint('LENGTH(title) >= 1', name='title_not_empty'),
    sa.CheckConstraint('actual_duration IS NULL OR actual_duration >= 0', name='actual_duration_non_negative'),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='completion_after_start'),
    sa.CheckConstraint('estimated_duration IS NULL OR estimated_duration > 0', name='estimated_duration_positive'),
    sa.CheckConstraint('max_retries >= 0', name='max_retries_non_negative'),
    sa.CheckConstraint('progress_percentage >= 0.0 AND progress_percentage <= 100.0', name='progress_bounds'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0.0 AND quality_score <= 10.0)', name='quality_score_bounds'),
    sa.CheckConstraint('retry_count >= 0', name='retry_count_non_negative'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_agent_status', 'tasks', ['assigned_agent_id', 'status'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_hierarchy', 'tasks', ['parent_task_id', 'status'], unique=False)
    op.create_index('idx_tasks_namespace_status', 'tasks', ['namespace', 'status'], unique=False)
    op.create_index('idx_tasks_performance', 'tasks', ['quality_score', 'actual_duration'], unique=False)
    op.create_index('idx_tasks_priority_status', 'tasks', ['priority', 'status'], unique=False)
    op.create_index('idx_tasks_progress', 'tasks', ['progress_percentage'], unique=False)
    op.create_index('idx_tasks_retry', 'tasks', ['retry_count', 'max_retries'], unique=False)
    op.create_index('idx_tasks_scheduled', 'tasks', ['scheduled_at'], unique=False)
    op.create_index('idx_tasks_type_status', 'tasks', ['task_type', 'status'], unique=False)
    op.create_index('idx_tasks_workflow', 'tasks', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_access_level'), 'tasks', ['access_level'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_agent_id'), 'tasks', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_namespace'), 'tasks', ['namespace'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_workflow_id'), 'tasks', ['workflow_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False, comment='Unique username (2-64 characters)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('password_hash', sa.Text(), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('password_salt', sa.Text(), nullable=False, comment='Password salt for additional security'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='Count of failed login attempts'),
    sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last failed login'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='IP address of last login'),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'locked', 'pending', name='userstatus'), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False, comment='List of user roles'),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='Additional granular permissions'),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False, comment='Multi-factor authentication enabled'),
    sa.Column('mfa_secret', sa.Text(), nullable=True, comment='TOTP secret for MFA'),
    sa.Column('backup_codes', sa.JSON(), nullable=True, comment='MFA backup codes'),
    sa.Column('force_password_change', sa.Boolean(), nullable=False, comment='Force password change on next login'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='When password was last changed'),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False, comment='Session timeout in minutes'),
    sa.Column('preferred_agent_id', sa.Text(), nullable=True, comment='Preferred agent for operations'),
    sa.Column('agent_namespace', sa.Text(), nullable=False, comment="User's agent namespace"),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='Username of user who created this account'),
    sa.Column('last_modified_by', sa.String(length=64), nullable=True, comment='Username of user who last modified this account'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email_status', 'users', ['email', 'status'], unique=False)
    op.create_index('ix_user_namespace', 'users', ['agent_namespace'], unique=False)
    op.create_index('ix_user_status_active', 'users', ['status', 'last_login_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workflows',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workflow_type', sa.Enum('SEQUENTIAL', 'PARALLEL', 'CONDITIONAL', 'HYBRID', name='workflowtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('current_step_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('execution_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_step_index', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_created_by_status', 'workflows', ['created_by', 'status'], unique=False)
    op.create_index('ix_workflow_last_executed', 'workflows', ['last_executed_at'], unique=False)
    op.create_index('ix_workflow_status_type', 'workflows', ['status', 'workflow_type'], unique=False)
    op.create_index(op.f('ix_workflows_completed_at'), 'workflows', ['completed_at'], unique=False)
    op.create_index(op.f('ix_workflows_created_by'), 'workflows', ['created_by'], unique=False)
    op.create_index(op.f('ix_workflows_last_executed_at'), 'workflows', ['last_executed_at'], unique=False)
    op.create_index(op.f('ix_workflows_name'), 'workflows', ['name'], unique=False)
    op.create_index(op.f('ix_workflows_started_at'), 'workflows', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('ix_workflows_workflow_type'), 'workflows', ['workflow_type'], unique=False)
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(length=32), nullable=False, comment='Public key identifier'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Human-readable key name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Key description and purpose'),
    sa.Column('key_hash', sa.Text(), nullable=False, comment='Hashed API key value'),
    sa.Column('key_prefix', sa.String(length=8), nullable=False, comment='Key prefix for identification (first 8 chars)'),
    sa.Column('scopes', sa.JSON(), nullable=False, comment='API key access scopes'),
    sa.Column('allowed_ips', sa.JSON(), nullable=True, comment='IP addresses allowed to use this key'),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True, comment='Custom rate limit for this key'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Key expiration timestamp'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='When key was last used'),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True, comment='IP address of last use'),
    sa.Column('total_requests', sa.Integer(), nullable=False, comment='Total requests made with this key'),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False, comment='JSON metadata'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_key_active', 'api_keys', ['is_active', 'expires_at'], unique=False)
    op.create_index('ix_api_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('ix_api_key_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('memory_consolidations',
    sa.Column('source_memory_ids', sa.JSON(), nullable=False, comment='Source memory IDs that were consolidated'),
    sa.Column('consolidated_memory_id', sa.String(length=36), nullable=False, comment='Resulting consolidated memory'),
    sa.Column('consolidation_type', sa.Text(), nullable=False, comment='Type: summary, merge, compress, etc.'),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('consolidation_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['consolidated_memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_consolidations_agent_id'), 'memory_consolidations', ['agent_id'], unique=False)
    op.create_table('memory_sharing',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('shared_with_agent_id', sa.Text(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=False, comment='Permission level: read, write, delete'),
    sa.Column('shared_by_agent_id', sa.Text(), nullable=False, comment='Agent who shared the memory'),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the sharing expires'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('memory_id', 'shared_with_agent_id', 'id')
    )
    op.create_index('ix_sharing_agent', 'memory_sharing', ['shared_with_agent_id', 'shared_at'], unique=False)
    op.create_index('ix_sharing_expires', 'memory_sharing', ['expires_at'], unique=False)
    op.create_table('pattern_usage_history',
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=True, comment='Execution time in seconds'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='Whether the pattern usage was successful'),
    sa.Column('context_data', sa.JSON(), nullable=True, comment='Context information about the usage'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['pattern_id'], ['learning_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_usage_history_agent_time', 'pattern_usage_history', ['agent_id', 'used_at'], unique=False)
    op.create_index('idx_pattern_usage_history_pattern_time', 'pattern_usage_history', ['pattern_id', 'used_at'], unique=False)
    op.create_index(op.f('ix_pattern_usage_history_agent_id'), 'pattern_usage_history', ['agent_id'], unique=False)
    op.create_index(op.f('ix_pattern_usage_history_pattern_id'), 'pattern_usage_history', ['pattern_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.String(length=64), nullable=False, comment='Unique token identifier'),
    sa.Column('token_hash', sa.Text(), nullable=False, comment='Hashed refresh token value'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expiration timestamp'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key UUID (string format)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_token_user', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_index('ix_refresh_token_valid', 'refresh_tokens', ['is_revoked', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_id'), 'refresh_tokens', ['token_id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('cpu_time_seconds', sa.Float(), nullable=True),
    sa.Column('memory_peak_mb', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_executions_started_at', 'workflow_executions', ['started_at'], unique=False)
    op.create_index('idx_workflow_executions_status', 'workflow_executions', ['status'], unique=False)
    op.create_index('idx_workflow_executions_triggered_by', 'workflow_executions', ['triggered_by'], unique=False)
    op.create_index('idx_workflow_executions_workflow_id', 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('workflow_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('schedule_expression', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('successful_runs', sa.Integer(), nullable=True),
    sa.Column('failed_runs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_schedules_is_active', 'workflow_schedules', ['is_active'], unique=False)
    op.create_index('idx_workflow_schedules_next_run_at', 'workflow_schedules', ['next_run_at'], unique=False)
    op.create_index('idx_workflow_schedules_workflow_id', 'workflow_schedules', ['workflow_id'], unique=False)
    op.create_table('workflow_step_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_execution_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=200), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_executions_status', 'workflow_step_executions', ['status'], unique=False)
    op.create_index('idx_step_executions_step_name', 'workflow_step_executions', ['step_name'], unique=False)
    op.create_index('idx_step_executions_workflow_execution_id', 'workflow_step_executions', ['workflow_execution_id'], unique=False)
    op.create_table('workflow_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_execution_id', sa.String(length=36), nullable=False),
    sa.Column('step_execution_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('function', sa.String(length=100), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['step_execution_id'], ['workflow_step_executions.id'], ),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_logs_level', 'workflow_execution_logs', ['level'], unique=False)
    op.create_index('idx_execution_logs_timestamp', 'workflow_execution_logs', ['timestamp'], unique=False)
    op.create_index('idx_execution_logs_workflow_execution_id', 'workflow_execution_logs', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_execution_logs_workflow_execution_id', table_name='workflow_execution_logs')
    op.drop_index('idx_execution_logs_timestamp', table_name='workflow_execution_logs')
    op.drop_index('idx_execution_logs_level', table_name='workflow_execution_logs')
    op.drop_table('workflow_execution_logs')
    op.drop_index('idx_step_executions_workflow_execution_id', table_name='workflow_step_executions')
    op.drop_index('idx_step_executions_step_name', table_name='workflow_step_executions')
    op.drop_index('idx_step_executions_status', table_name='workflow_step_executions')
    op.drop_table('workflow_step_executions')
    op.drop_index('idx_workflow_schedules_workflow_id', table_name='workflow_schedules')
    op.drop_index('idx_workflow_schedules_next_run_at', table_name='workflow_schedules')
    op.drop_index('idx_workflow_schedules_is_active', table_name='workflow_schedules')
    op.drop_table('workflow_schedules')
    op.drop_index('idx_workflow_executions_workflow_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_triggered_by', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_started_at', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_valid', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pattern_usage_history_pattern_id'), table_name='pattern_usage_history')
    op.drop_index(op.f('ix_pattern_usage_history_agent_id'), table_name='pattern_usage_history')
    op.drop_index('idx_pattern_usage_history_pattern_time', table_name='pattern_usage_history')
    op.drop_index('idx_pattern_usage_history_agent_time', table_name='pattern_usage_history')
    op.drop_table('pattern_usage_history')
    op.drop_index('ix_sharing_expires', table_name='memory_sharing')
    op.drop_index('ix_sharing_agent', table_name='memory_sharing')
    op.drop_table('memory_sharing')
    op.drop_index(op.f('ix_memory_consolidations_agent_id'), table_name='memory_consolidations')
    op.drop_table('memory_consolidations')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index('ix_api_key_user_active', table_name='api_keys')
    op.drop_index('ix_api_key_prefix', table_name='api_keys')
    op.drop_index('ix_api_key_active', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_workflows_workflow_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_status'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_started_at'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_name'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_last_executed_at'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_created_by'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_completed_at'), table_name='workflows')
    op.drop_index('ix_workflow_status_type', table_name='workflows')
    op.drop_index('ix_workflow_last_executed', table_name='workflows')
    op.drop_index('ix_workflow_created_by_status', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_status_active', table_name='users')
    op.drop_index('ix_user_namespace', table_name='users')
    op.drop_index('ix_user_email_status', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_workflow_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_namespace'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_agent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_access_level'), table_name='tasks')
    op.drop_index('idx_tasks_workflow', table_name='tasks')
    op.drop_index('idx_tasks_type_status', table_name='tasks')
    op.drop_index('idx_tasks_scheduled', table_name='tasks')
    op.drop_index('idx_tasks_retry', table_name='tasks')
    op.drop_index('idx_tasks_progress', table_name='tasks')
    op.drop_index('idx_tasks_priority_status', table_name='tasks')
    op.drop_index('idx_tasks_performance', table_name='tasks')
    op.drop_index('idx_tasks_namespace_status', table_name='tasks')
    op.drop_index('idx_tasks_hierarchy', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_agent_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_templates_template_id'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_namespace'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_is_active'), table_name='task_templates')
    op.drop_index('idx_task_templates_usage', table_name='task_templates')
    op.drop_index('idx_task_templates_success', table_name='task_templates')
    op.drop_index('idx_task_templates_namespace', table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_timestamp'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_severity'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_session_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_risk_score'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_hash'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_client_ip'), table_name='security_audit_logs')
    op.drop_index('idx_audit_logs_timestamp_severity', table_name='security_audit_logs')
    op.drop_index('idx_audit_logs_event_type_timestamp', table_name='security_audit_logs')
    op.drop_index('idx_audit_logs_client_ip', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index(op.f('ix_personas_type'), table_name='personas')
    op.drop_index(op.f('ix_personas_role'), table_name='personas')
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_index(op.f('ix_personas_last_active_at'), table_name='personas')
    op.drop_index(op.f('ix_personas_is_active'), table_name='personas')
    op.drop_index('ix_persona_type_active', table_name='personas')
    op.drop_index('ix_persona_role_active', table_name='personas')
    op.drop_index('ix_persona_active_last_active', table_name='personas')
    op.drop_table('personas')
    op.drop_index('ix_pattern_confidence', table_name='memory_patterns')
    op.drop_index('ix_pattern_agent_type', table_name='memory_patterns')
    op.drop_index(op.f('ix_memory_patterns_namespace'), table_name='memory_patterns')
    op.drop_index(op.f('ix_memory_patterns_is_active'), table_name='memory_patterns')
    op.drop_index(op.f('ix_memory_patterns_agent_id'), table_name='memory_patterns')
    op.drop_table('memory_patterns')
    op.drop_index('ix_memory_importance', table_name='memories')
    op.drop_index('ix_memory_expires', table_name='memories')
    op.drop_index('ix_memory_agent_namespace', table_name='memories')
    op.drop_index('ix_memory_accessed', table_name='memories')
    op.drop_index('ix_memory_access_level', table_name='memories')
    op.drop_index(op.f('ix_memories_namespace'), table_name='memories')
    op.drop_index(op.f('ix_memories_expires_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_agent_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_accessed_at'), table_name='memories')
    op.drop_index(op.f('ix_memories_access_level'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_learning_patterns_namespace'), table_name='learning_patterns')
    op.drop_index(op.f('ix_learning_patterns_category'), table_name='learning_patterns')
    op.drop_index(op.f('ix_learning_patterns_agent_id'), table_name='learning_patterns')
    op.drop_index('idx_learning_patterns_usage', table_name='learning_patterns')
    op.drop_index('idx_learning_patterns_last_used', table_name='learning_patterns')
    op.drop_index('idx_learning_patterns_category_access', table_name='learning_patterns')
    op.drop_index('idx_learning_patterns_agent_namespace', table_name='learning_patterns')
    op.drop_table('learning_patterns')
    op.drop_index('idx_api_audit_log_user_id', table_name='api_audit_log')
    op.drop_index('idx_api_audit_log_endpoint', table_name='api_audit_log')
    op.drop_index('idx_api_audit_log_created_at', table_name='api_audit_log')
    op.drop_table('api_audit_log')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_namespace'), table_name='agents')
    op.drop_index(op.f('ix_agents_last_active_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_index('ix_agent_type_status', table_name='agents')
    op.drop_index('ix_agent_status_active', table_name='agents')
    op.drop_index('ix_agent_org_namespace', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_teams_team_id'), table_name='agent_teams')
    op.drop_index(op.f('ix_agent_teams_is_active'), table_name='agent_teams')
    op.drop_table('agent_teams')
    op.drop_index(op.f('ix_agent_namespaces_namespace'), table_name='agent_namespaces')
    op.drop_index(op.f('ix_agent_namespaces_is_active'), table_name='agent_namespaces')
    op.drop_table('agent_namespaces')
    # ### end Alembic commands ###
