#!/usr/bin/env bash
#
# Document Registry Installation Script
#
# Purpose: Install and configure document registry system
# Created: 2025-11-03
# Created by: Artemis (Technical Perfectionist)
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")
HOOKS_DIR="$REPO_ROOT/.git/hooks"
PRE_COMMIT_HOOK="$HOOKS_DIR/pre-commit"
REGISTRY_HOOK_SOURCE="$REPO_ROOT/hooks/pre-commit-document-registry"
LOGS_DIR="$REPO_ROOT/logs"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Trinitas Document Registry Installer  ${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Step 1: Check prerequisites
echo -e "${YELLOW}[1/6]${NC} Checking prerequisites..."

if ! command -v python3 &> /dev/null; then
    echo -e "${RED}❌ Python 3 is required but not installed${NC}"
    exit 1
fi

if ! command -v git &> /dev/null; then
    echo -e "${RED}❌ Git is required but not installed${NC}"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
echo -e "${GREEN}✅ Python ${PYTHON_VERSION} found${NC}"

# Step 2: Install Python dependencies
echo ""
echo -e "${YELLOW}[2/6]${NC} Installing Python dependencies..."

if ! python3 -c "import yaml" 2>/dev/null; then
    echo "  Installing PyYAML..."
    pip3 install --user PyYAML || {
        echo -e "${RED}❌ Failed to install PyYAML${NC}"
        exit 1
    }
fi

echo -e "${GREEN}✅ Dependencies installed${NC}"

# Step 3: Create directories
echo ""
echo -e "${YELLOW}[3/6]${NC} Creating directories..."

mkdir -p "$LOGS_DIR"
mkdir -p "$REPO_ROOT/docs"

echo -e "${GREEN}✅ Directories created${NC}"

# Step 4: Initialize registry
echo ""
echo -e "${YELLOW}[4/6]${NC} Initializing document registry..."

REGISTRY_SCRIPT="$REPO_ROOT/scripts/update_document_registry.py"
chmod +x "$REGISTRY_SCRIPT"

if [ ! -f "$REPO_ROOT/docs/DOCUMENT_REGISTRY.yaml" ]; then
    echo "  Scanning and registering documents..."
    python3 "$REGISTRY_SCRIPT" init || {
        echo -e "${RED}❌ Failed to initialize registry${NC}"
        exit 1
    }
else
    echo "  Registry already exists, skipping initialization"
fi

echo -e "${GREEN}✅ Registry initialized${NC}"

# Step 5: Validate registry
echo ""
echo -e "${YELLOW}[5/6]${NC} Validating registry..."

if python3 "$REGISTRY_SCRIPT" validate; then
    echo -e "${GREEN}✅ Registry validation passed${NC}"
else
    echo -e "${YELLOW}⚠️  Registry has warnings (non-blocking)${NC}"
fi

# Step 6: Install git hook
echo ""
echo -e "${YELLOW}[6/6]${NC} Installing git pre-commit hook..."

if [ ! -d "$HOOKS_DIR" ]; then
    echo -e "${YELLOW}⚠️  .git/hooks directory not found${NC}"
    echo -e "${YELLOW}⚠️  Skipping hook installation${NC}"
else
    # Make hook executable
    chmod +x "$REGISTRY_HOOK_SOURCE"

    # Check if pre-commit hook already exists
    if [ -f "$PRE_COMMIT_HOOK" ]; then
        echo "  Existing pre-commit hook found"

        # Check if our hook is already included
        if grep -q "pre-commit-document-registry" "$PRE_COMMIT_HOOK"; then
            echo -e "${GREEN}✅ Document registry hook already installed${NC}"
        else
            echo "  Appending document registry hook to existing pre-commit"

            # Backup existing hook
            cp "$PRE_COMMIT_HOOK" "$PRE_COMMIT_HOOK.backup"
            echo "  (Backup saved: $PRE_COMMIT_HOOK.backup)"

            # Append our hook
            cat >> "$PRE_COMMIT_HOOK" << 'EOF'

# ============================================================
# Trinitas Document Registry Hook
# ============================================================
REGISTRY_HOOK="$(git rev-parse --show-toplevel)/hooks/pre-commit-document-registry"
if [ -f "$REGISTRY_HOOK" ]; then
    bash "$REGISTRY_HOOK"
fi

EOF

            echo -e "${GREEN}✅ Document registry hook appended${NC}"
        fi
    else
        # Create new pre-commit hook
        cat > "$PRE_COMMIT_HOOK" << 'EOF'
#!/usr/bin/env bash
#
# Git Pre-commit Hook
# Auto-generated by Trinitas Document Registry Installer
#

# Trinitas Document Registry Hook
REGISTRY_HOOK="$(git rev-parse --show-toplevel)/hooks/pre-commit-document-registry"
if [ -f "$REGISTRY_HOOK" ]; then
    bash "$REGISTRY_HOOK"
fi

EOF

        chmod +x "$PRE_COMMIT_HOOK"
        echo -e "${GREEN}✅ Pre-commit hook created${NC}"
    fi
fi

# Generate index
echo ""
echo -e "${YELLOW}Generating INDEX.md...${NC}"
python3 "$REGISTRY_SCRIPT" index
echo -e "${GREEN}✅ INDEX.md generated${NC}"

# Success summary
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Installation completed successfully!${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Review the generated registry:"
echo "     ${YELLOW}cat docs/DOCUMENT_REGISTRY.yaml${NC}"
echo ""
echo "  2. Review the generated index:"
echo "     ${YELLOW}cat docs/INDEX.md${NC}"
echo ""
echo "  3. Add a new document:"
echo "     ${YELLOW}python3 scripts/update_document_registry.py add <file>${NC}"
echo ""
echo "  4. Validate registry:"
echo "     ${YELLOW}python3 scripts/update_document_registry.py validate${NC}"
echo ""
echo "  5. The pre-commit hook will automatically:"
echo "     - Update registry for changed documentation files"
echo "     - Validate registry integrity"
echo "     - Regenerate INDEX.md"
echo ""
echo -e "${GREEN}Documentation registry is ready! 🚀${NC}"
echo ""
